import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const messapia = localFont({
  src: [
    {
      path: "./fonts/Messapia-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Messapia-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-messapia",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${messapia.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
